version: '3.9'

services:
  postgres-db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: productos_db
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dotnet-network

  datatier:
    build:
      context: .
      dockerfile: ./DataTier_Prov/Dockerfile
    container_name: datatier
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Port=5432;Database=productos_db;Username=admin;Password=admin123
    networks:
      - dotnet-network

  businesstier:
    build:
      context: .
      dockerfile: ./BussinessTier_Prov/Dockerfile
    container_name: businesstier
    ports:
      - "8081:8081"
    depends_on:
      - datatier
    environment:
      - DataTierUrl=http://datatier:8080
    networks:
      - dotnet-network

networks:
  dotnet-network:
    driver: bridge
