version: '3.9'

services:
  postgres-db:
    image: postgres:16
    container_name: postgres-db2
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: productos_db
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dotnet-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d TestDb"]
      interval: 10s
      timeout: 5s
      retries: 5

  dotnet-app:
    build: .
    container_name: dotnet-app
    ports:
      - "8080:8080"
    depends_on:
      postgres-db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Port=5432;Database=TestDb;Username=admin;Password=admin123
    networks:
      - dotnet-network

networks:
  dotnet-network:
    driver: bridge

volumes:
  postgres_data: